/*
JAKUB WAWAK
ALL RIGHTS RESERVED.
kubawawak@gmail.com
 */
package shoplistmaker;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ustawienia_window extends javax.swing.JDialog {

    /**
     * Creates new form ustawienia_window
     */
    InfoHandler program_info;
    public ustawienia_window(java.awt.Frame parent, boolean modal,InfoHandler act_inf) {
        super(parent, modal);
        program_info = act_inf;
        
        initComponents();
        setLocationRelativeTo(null);
        imie_label.setText(act_inf.to_pass.get_imie());
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imie_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mod_imie_button = new javax.swing.JButton();
        mod_sciezka_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        wyslij_slownik_button = new javax.swing.JButton();
        podglad_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Twoje Imie:");

        imie_label.setText("jLabel2");

        jLabel2.setText("Ścieżka Słownika:");

        mod_imie_button.setText("Modyfikuj..");
        mod_imie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_imie_buttonActionPerformed(evt);
            }
        });

        mod_sciezka_button.setText("Modyfikuj..");
        mod_sciezka_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_sciezka_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Ustawienia SLM");

        wyslij_slownik_button.setText("Wyślij swój słownik");
        wyslij_slownik_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyslij_slownik_buttonActionPerformed(evt);
            }
        });

        podglad_button.setText("Podgląd");
        podglad_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podglad_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(podglad_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(imie_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mod_imie_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mod_sciezka_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(wyslij_slownik_button, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(imie_label)
                    .addComponent(mod_imie_button))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(podglad_button)
                    .addComponent(mod_sciezka_button))
                .addGap(31, 31, 31)
                .addComponent(wyslij_slownik_button)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mod_imie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_imie_buttonActionPerformed
        String nowe_imie = JOptionPane.showInputDialog("Podaj nowe imie:");
        try {
            program_info.to_pass.change_imie(nowe_imie);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ustawienia_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        imie_label.setText(program_info.to_pass.get_imie());
    }//GEN-LAST:event_mod_imie_buttonActionPerformed

    private void mod_sciezka_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_sciezka_buttonActionPerformed
        JFileChooser myFileChooser = new JFileChooser();
        myFileChooser.setDialogTitle("Zmiana lokalizacji pliku slownikowego");

        if(myFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            String path = myFileChooser.getSelectedFile().getAbsolutePath();

            if(path.contains("dict")&&path.endsWith(".txt")){
                try {
                    program_info.to_pass.change_path(path);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ustawienia_window.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        JOptionPane.showMessageDialog(this,program_info.to_pass.get_dict_path());
    }//GEN-LAST:event_mod_sciezka_buttonActionPerformed

    private void podglad_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podglad_buttonActionPerformed
        JOptionPane.showMessageDialog(this,program_info.to_pass.get_dict_path());
    }//GEN-LAST:event_podglad_buttonActionPerformed

    private void wyslij_slownik_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyslij_slownik_buttonActionPerformed
        JOptionPane.showMessageDialog(this, "Ta funkcja zostanie dodana w wersji v1.3.1");
    }//GEN-LAST:event_wyslij_slownik_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imie_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mod_imie_button;
    private javax.swing.JButton mod_sciezka_button;
    private javax.swing.JButton podglad_button;
    private javax.swing.JButton wyslij_slownik_button;
    // End of variables declaration//GEN-END:variables
}
