/*
JAKUB WAWAK
ALL RIGHTS RESERVED.
kubawawak@gmail.com
 */
package shoplistmaker;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ustawienia_window extends javax.swing.JDialog {

    /**
     * Creates new form ustawienia_window
     */
    InfoHandler program_info;
    public ustawienia_window(java.awt.Frame parent, boolean modal,InfoHandler act_inf) {
        super(parent, modal);
        program_info = act_inf;
        
        initComponents();
        setLocationRelativeTo(null);
        imie_label.setText(act_inf.to_pass.get_imie());
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imie_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mod_imie_button = new javax.swing.JButton();
        mod_sciezka_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        wyslij_slownik_button = new javax.swing.JButton();
        podglad_button = new javax.swing.JButton();
        merge_dictionaries_button = new javax.swing.JButton();
        database_login_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Your Name");

        imie_label.setText("jLabel2");

        jLabel2.setText("Path of dictionary file");

        mod_imie_button.setText("Edit");
        mod_imie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_imie_buttonActionPerformed(evt);
            }
        });

        mod_sciezka_button.setText("Edit");
        mod_sciezka_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_sciezka_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("SLM SETTINGS");

        wyslij_slownik_button.setText("Send your dictionary");
        wyslij_slownik_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyslij_slownik_buttonActionPerformed(evt);
            }
        });

        podglad_button.setText("Show path");
        podglad_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podglad_buttonActionPerformed(evt);
            }
        });

        merge_dictionaries_button.setText("Merge dictionaries");

        database_login_button.setText("Login to database");
        database_login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                database_login_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wyslij_slownik_button, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(database_login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(merge_dictionaries_button, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(podglad_button)
                        .addGap(30, 30, 30)
                        .addComponent(mod_sciezka_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19)
                        .addComponent(imie_label)
                        .addGap(31, 31, 31)
                        .addComponent(mod_imie_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(imie_label)
                    .addComponent(mod_imie_button))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(podglad_button)
                    .addComponent(mod_sciezka_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(database_login_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wyslij_slownik_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(merge_dictionaries_button)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mod_imie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_imie_buttonActionPerformed
        String nowe_imie = JOptionPane.showInputDialog("Type your name:");
        try {
            program_info.to_pass.change_imie(nowe_imie);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ustawienia_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        imie_label.setText(program_info.to_pass.get_imie());
    }//GEN-LAST:event_mod_imie_buttonActionPerformed

    private void mod_sciezka_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_sciezka_buttonActionPerformed
        JFileChooser myFileChooser = new JFileChooser();
        myFileChooser.setDialogTitle("You changed the dictionary path");

        if(myFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            String path = myFileChooser.getSelectedFile().getAbsolutePath();

            if(path.contains("dict")&&path.endsWith(".txt")){
                try {
                    program_info.to_pass.change_path(path);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ustawienia_window.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        JOptionPane.showMessageDialog(this,program_info.to_pass.get_dict_path());
    }//GEN-LAST:event_mod_sciezka_buttonActionPerformed

    private void podglad_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podglad_buttonActionPerformed
        JOptionPane.showMessageDialog(this,program_info.to_pass.get_dict_path());
    }//GEN-LAST:event_podglad_buttonActionPerformed

    private void wyslij_slownik_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyslij_slownik_buttonActionPerformed
        DictReader act = new DictReader("",program_info);
        String email = JOptionPane.showInputDialog("Type e-mail");
        if ( email.contains("@") ){
            try {
                MailSender ms = new MailSender(act,email);
                ms.run();
                JOptionPane.showMessageDialog(this, "Dictionary was sent");
            } catch (MessagingException ex) {
                Logger.getLogger(ustawienia_window.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ustawienia_window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_wyslij_slownik_buttonActionPerformed

    private void database_login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_database_login_buttonActionPerformed
        JOptionPane.showMessageDialog(this, "This function will be added in the future update");
    }//GEN-LAST:event_database_login_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton database_login_button;
    private javax.swing.JLabel imie_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton merge_dictionaries_button;
    private javax.swing.JButton mod_imie_button;
    private javax.swing.JButton mod_sciezka_button;
    private javax.swing.JButton podglad_button;
    private javax.swing.JButton wyslij_slownik_button;
    // End of variables declaration//GEN-END:variables
}
